version: '3'
services:
  backend:
    container_name: td_backend
    image: td_backend:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - td_app
  frontend:
    container_name: td_frontend
    image: td_frontend:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - td_app
networks:
  td_app:
    driver: bridge